### ISSUE TITLE
Release for SB 2.x

### ISSUE THREAD

**Issue by geoand** [opentracing-contrib/java-spring-web#87]
We should probably also perform a release supporting SB 2.x (most likely SB 2.1.x).

@pavolloffay How would you like to organize the code for such a release? Would you like to have a separate branch for such a release?
Also, what would you like to do about the release versions?

**Comment by pavolloffay** [comment]
we could do it in master and use branch for 1.x. About the version maybe release SB as 0.2x.x ?

**Comment by geoand** [comment]
I agree for the branch but I am a little confused about the versioning scheme :P

**Comment by objectiser** [comment]
I think it might need a major version bump - so start releasing 1.x - as otherwise, if fixes are required on the SB 1.x branch, then it would require a release of 0.x which would become confused with the SB 2.x compatible versions.

Would suggest have a 0.x branch (as it is based on this libraries version), and master then becomes SB2 compatible releasing 1.x versions of this lib.

**Comment by pavolloffay** [comment]
are there any breaking changes in SB2 web package which would influence us?

**Comment by geoand** [comment]
@pavolloffay I haven't tested yet, but I don't expect there to be any breaking changes :)

FWIW, I like the suggestion from @objectiser on how to handle the versions

**Comment by geoand** [comment]
Looks like there are some mockito issues that I need to sort out....
